services:
  hub:
    image: selenium/hub:latest
    restart: always
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
      image: selenium/node-firefox:latest
      shm_size: '2g'
      depends_on:
        - hub
      deploy:
        replicas: 0
      env_file: .env
